# Plot spatial representativeness check: full study box vs Puglia sub-region.
# Reads outputs/tables/spatial_check.csv (generated by spatial_representativeness.R).
# Output: outputs/figures/spatial_representativeness.png

library(here)
library(tidyverse)
library(tidybayes)
library(patchwork)

dat <- readr::read_csv(here("outputs", "tables", "spatial_check.csv"),
                       show_col_types = FALSE) |>
  mutate(
    temp_anom_full    = temp_full_C    - mean(temp_full_C),
    temp_anom_puglia  = temp_puglia_C  - mean(temp_puglia_C),
    prec_anom_full    = (precip_full_mm   - mean(precip_full_mm))   / mean(precip_full_mm)   * 100,
    prec_anom_puglia  = (precip_puglia_mm - mean(precip_puglia_mm)) / mean(precip_puglia_mm) * 100
  )

region_cols <- c("Full study box" = "grey30", "Puglia sub-region" = "#0072B2")

make_panel <- function(dat, y_full, y_puglia, y_lab, title) {
  plot_dat <- bind_rows(
    dat |> transmute(century, region = "Full study box",    value = .data[[y_full]]),
    dat |> transmute(century, region = "Puglia sub-region", value = .data[[y_puglia]])
  )

  ggplot(plot_dat, aes(x = century, y = value, colour = region, linetype = region)) +
    geom_hline(yintercept = 0, colour = "black", alpha = 0.3) +
    geom_line(linewidth = 1.0) +
    geom_point(size = 2.5) +
    scale_x_continuous(breaks = seq(1000, 1800, by = 100)) +
    scale_colour_manual(name = NULL, values = region_cols) +
    scale_linetype_manual(name = NULL,
                          values = c("Full study box" = "solid",
                                     "Puglia sub-region" = "dashed")) +
    labs(x = "Century", y = y_lab, title = title) +
    theme_tidybayes() +
    theme(
      text            = element_text(size = 14),
      plot.title      = element_text(face = "bold", size = 18),
      plot.tag        = element_text(face = "bold", size = 16),
      axis.text.x     = element_text(angle = 45, hjust = 1),
      legend.position = "bottom",
      plot.margin     = margin(10, 10, 10, 10)
    )
}

p_temp <- make_panel(dat,
  y_full   = "temp_anom_full",
  y_puglia = "temp_anom_puglia",
  y_lab    = "Temperature anomaly (°C)",
  title    = "Temperature: full box vs. Puglia sub-region")

p_prec <- make_panel(dat,
  y_full   = "prec_anom_full",
  y_puglia = "prec_anom_puglia",
  y_lab    = "Precipitation anomaly (%)",
  title    = "Precipitation: full box vs. Puglia sub-region")

p_combined <- (p_temp / p_prec) +
  plot_annotation(tag_levels = "A") &
  theme(plot.tag = element_text(face = "bold", size = 16))

ggsave(here("outputs", "figures", "spatial_representativeness.png"),
       p_combined, width = 10, height = 14, dpi = 300, bg = "white")

message("Saved: outputs/figures/spatial_representativeness.png")
